export const FUNNEL_CONFIG = {
  "debt-qualification": {
    title: "Debt Qualification",
    language: "Espanol",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "welcome_started", label: "Started Chat" },
      { event: "debt_selected", label: "Selected Debt Amount" },
      { event: "employment_selected", label: "Selected Employment" },
      { event: "prequalified", label: "Reached Call Screen" },
      { event: "call_click", label: "Clicked Call" },
    ],
  },
  "debt-relief-usa": {
    title: "Debt Relief USA",
    language: "Espanol",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "options_shown", label: "Saw Debt Options" },
      { event: "debt_selected", label: "Selected Debt Range" },
      { event: "qualified", label: "Reached Qualified Result" },
      { event: "call_click", label: "Clicked Call" },
    ],
  },
  "fe3-an-en": {
    title: "FE3 AN EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "quiz_submitted", label: "Submitted Quiz" },
      { event: "qualification_checked", label: "Passed Qualification Check" },
      { event: "advisor_ready", label: "Reached Advisor Ready" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe3-mc-en": {
    title: "FE3 MC EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "quiz_submitted", label: "Submitted Quiz" },
      { event: "qualification_checked", label: "Passed Qualification Check" },
      { event: "advisor_ready", label: "Reached Advisor Ready" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe4-an-en": {
    title: "FE4 AN EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "quiz_submitted", label: "Submitted Quiz" },
      { event: "qualification_checked", label: "Passed Qualification Check" },
      { event: "advisor_ready", label: "Reached Advisor Ready" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe4-mc-en": {
    title: "FE4 MC EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "quiz_submitted", label: "Submitted Quiz" },
      { event: "qualification_checked", label: "Passed Qualification Check" },
      { event: "advisor_ready", label: "Reached Advisor Ready" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe4-fj-en": {
    title: "FE4 FJ EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "quiz_submitted", label: "Submitted Quiz" },
      { event: "qualification_checked", label: "Passed Qualification Check" },
      { event: "advisor_ready", label: "Reached Advisor Ready" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe5-an-en": {
    title: "FE5 AN EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "welcome_started", label: "Started Chat" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "prequalified", label: "Reached Call Screen" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe5-jf-en": {
    title: "FE5 JF EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "welcome_started", label: "Started Chat" },
      { event: "age_selected", label: "Selected Age" },
      { event: "insurance_selected", label: "Selected Insurance" },
      { event: "prequalified", label: "Reached Call Screen" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe6-an-en": {
    title: "FE6 AN EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "options_shown", label: "Saw Age Options" },
      { event: "age_selected", label: "Selected Age" },
      { event: "qualified", label: "Reached Qualified Result" },
      { event: "call_click", label: "Clicked Final Call" },
    ],
  },
  "fe7-an-en": {
    title: "FE7 AN EN",
    language: "English",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "location_selected", label: "Confirmed Location" },
      { event: "benefit_selected", label: "Selected Benefit Status" },
      { event: "coverage_selected", label: "Selected Amount" },
      { event: "age_selected", label: "Selected Age" },
      { event: "name_submitted", label: "Submitted Name" },
      { event: "qualifying_started", label: "Started Qualifying" },
      { event: "qualified_popup", label: "Opened Qualification Popup" },
      { event: "call_click", label: "Clicked Call CTA" },
    ],
  },
  "iul-es": {
    title: "IUL ES",
    language: "Espanol",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "location_selected", label: "Confirmed Location" },
      { event: "benefit_selected", label: "Selected Benefit Status" },
      { event: "coverage_selected", label: "Selected Amount" },
      { event: "age_selected", label: "Selected Age" },
      { event: "name_submitted", label: "Submitted Name" },
      { event: "qualifying_started", label: "Started Qualifying" },
      { event: "qualified_popup", label: "Opened Qualification Popup" },
      { event: "claim_click", label: "Clicked Claim CTA" },
    ],
  },
  "iul-es2": {
    title: "IUL ES2",
    language: "Espanol",
    steps: [
      { event: "landing_view", label: "Landing View" },
      { event: "benefit_selected", label: "Selected Benefit Status" },
      { event: "coverage_selected", label: "Selected Amount" },
      { event: "age_selected", label: "Selected Age" },
      { event: "name_submitted", label: "Submitted Name" },
      { event: "claim_click", label: "Clicked Claim CTA" },
    ],
  },
} as const;
